### PR TITLE
Updated README.md to make it more readable

### PR DESCRIPTION
**Pull request by nbro**
Removed README.txt: no need to have 2 READMEs

### CODE REVIEW

**Comment by nbro** [comment]
@sgkasselau Do you accept pull requests? 

By the way, your code has bugs, so don't you want people to help you make this good software, or do you prefer to ship buggy software, as long as you're the only author? 

I'm just trying to understand if I should lose my time trying to make another pull request if you will just ignore it as "not valuable". Clearly, my previous pull request fixed some issues (no need for 2 READMEs), or just stick with my fork and make it actually the good version. Either way it's fine for me.

**Comment by sgkasselau** [comment]
@nbro I owe you an apology as well as an explanation. Maybe your future approach will change, maybe it won't.

First of all, apologies for force pushing and closing this pull request without comment. I had a narrow window to change my details on all my projects to be consistent for an opportunity I was chasing. I should have come back and explained, but things got complicated in my personal life around that same time. (I'll explain elsewhere sometime, if you're amenable to my suggestions below.)

I've not had a lot of capacity to do anything much until fairly recently.

Beyond the name and detail change (the reason why I forced pushed, and I hope you can understand why), perhaps obviously, this project is inactive, and the version you've forked from is a particularly dead branch of this code base with no future. It is essentially just a portfolio piece at this point.

I was working on a 2.0 version, back in the day - I got maybe 75% of the way through a giant refactor, to make this into a more general unsupervised machine learning platform, since I found AIXI had a lot of limits for what I was aiming for.

I'd implemented a number of drop-in learning algorithms to be used eventually in parallel. With the goal of training these algorithms simultaneously to find the best fit approach for a particularly environment, and - hopefully - even an ensemble learning approach better than just one algorithm. (I was contemplating a rename, since the changes are that significant.)

But I found that almost as limited. And so I didn't feel it was worth tidying up the work for publication and broader use.

My research focus is now in a different area, accordingly.

If I was to resume work on this project, it would be to ultimately revive this unpublished 2.0 branch. Which doesn't share a commit history with your codebase, unfortunately.

Speaking of your codebase, I appreciate the work you've done modernising the code to Python 3.9. PEP8 and Black usage is a nice touch. And I definitely do appreciate bug fixes.

However, I don't appreciate you removing my name as author, or my contact details, though - any version of them - from the human-readable documentation. Beyond being rude, I see that as being in violation of the attribution clause of the licence.

If you wanted to make good on this, here's what I'd like you to do:

- restore my author credit to the README files on your fork - as SG Kassel, please.
- rewrite the author name on the commit history for my commits, as I did in this version of this codebase. (I'm uncomfortable working on a codebase containing my old name, as perhaps you can guess.) 

If you're amenable to getting back into compliance with the licence (and I do understand that's going to break your fork, apologies) I could help port the work from your fork on top of the official branch. We could do a 1.9 release with your work, and work together on getting my refactored 2.0 integrated into this as a combined version.

And I would be happy to add your name as a co-author and maintainer for 1.9 and forward then, since you've definitely done a non-trivial amount of work.

What do you think?

**Comment by nbro** [comment]
@sgkasselau Hi. Thanks for answering. 

I removed the section "Contact the author" from my README.md file **NOT** because I didn't want to give you proper attribution. Of course, **you are the copyright holder of the code that YOU have written**. In fact, if you look into my `setup.py`, you're still an author there (as I think you already saw), but I also added my self there as an author and maintainer of my fork because I significantly changed the code by removing the support for Python 2, as you already know. The only reason why I removed that section was because I thought that you would not accept my pull requests, so there was no point in leaving there info to contact you, if my code now is different and I am maintaining it. Moreover, I removed other things from the `README.md` - I did that because I only wanted to leave what I think is really necessary in the README - for example, there is no need to have the section `Script usage` - we can simply tell the user to do `python aixi.py --help` (as I did in my fork).

It seems that the last public changes that you made to your repo, before my first commit in my fork, were to remove the email from the `setup.py` [here](https://github.com/sgkasselau/pyaixi/commit/39afd4cf14efeef57087d7121a525f214cf5c077) and change your name (as you said). So, my first commit starts after [this](https://github.com/sgkasselau/pyaixi/commit/8f4fe33b4dffd4b8dfa104e319361a6f3524d391) commit.

I spent a significant amount of time making the changes that I made to my repo. I don't know it it makes sense to ignore them and start again from your unpublished branch, which seems to be what you're suggesting.

I don't know what your 1.8 version exactly contains. Can you publish it? It seems that the last version you published was 1.0.4.post. 

Anyway, honestly, I don't think it's a good idea to change this project from being about pyaixi to something that contains many other algorithms and being about unsupervised learning algorithms in general. It might be better to start a new package that includes this package as a dependency, if you want e.g. to compare pyaixi with other algorithms. 

If you want to incorporate my changes, there are 2 main alternatives 

### Alternative 1

1. integrate your last changes starting from [this commit](https://github.com/sgkasselau/pyaixi/commit/aba7d48e3233bf9db57c8382bf1c2dc39385108f) (which are not many) into my fork
2. then add my commits on top of that
3. I then make a pull request

### Alternative 2

I can simply make a pull request with my changes, but you would need to deal with some conflicts (not many because the only files that are different between our versions are `README.md` and `setup.py`) - maybe this alternative is even better and would save me from having to do something tricky git moves. 

However, note that I changed the version of my fork to 2.0.0 because I dropped the python 2 support, which is a major change.

**Comment by nbro** [comment]
Speaking of licenses, the creative commons licenses is not a common license used in software. Can you clarify why you chose it? Why not MIT, for example? Right now, I don't know all the details of this license, but, if possible, I would recommend to change the license to MIT, which is more common, simpler and still requires people to give you attribution.

I see that the original C++ implementation, which you based your implementation on, also has the same license [here](https://github.com/moridinamael/mc-aixi/blob/master/license.txt), but I don't think that you need to license this package under the same license only because of that. 

The "ShareAlike" part seems to imply that, if you remix, transform or build upon, you must redistribute the contributions under the same license, but the question is: although you based your implementation on the C++ ones, does that imply that you built upon it? I don't think so. I think that building upon, here, means that you develop some software on top of the C++ version, which is not the case. You also didn't remix or transform the original one. You created a completely new software, although inspired by the C++ version.

**Comment by sgkasselau** [comment]
@nbro Thank you for your explanation.

Without getting into the weeds of the attribution stuff too much? (I do want to work together with you, as mentioned.)

Yes, I do understand how my copyright works here, and I understand there are still references to my (old) name and details throughout your fork.

But you can understand how this looked to me, right? Especially when you've gone to such lengths to list other projects in the human-readable documentation - you haven't listed who literally created the codebase you're working on. Not a word, not even a link.

It felt - and others I asked agreed with me - like you were trying to remove references to me, so that you could claim credit for the whole project.

Now, I'm going to assume that's not your intent. Primarily because I've seen how careful you've been to list these other projects, to try to be helpful. So I'm happy to accept that this was an oversight.

And it sounds like we're moving forward to some sort of agreement of how to fix this, and work together. Good!

But before we move on - please do understand I'm going to assert my authorship here, and going to be very particular about that.

So to clarify: whatever we decide - whatever happens next, or doesn't - I want you to understand that the conditions I outlined in my previous comment are non-negotiable for your continued use of this codebase. Here they are again:

- restore my author credit to the README files on your fork - as SG Kassel, please.
- rewrite the author name on the commit history for my commits, as I did in my version of this codebase (this is very important to me)

--

Now, with that bit of unpleasantness (hopefully) out of the way, if you're still on board to work together?

Let's try your Alternative 2 - presumably that means you're building your work again on top of the current master? (Oof, sorry!)

If so, let's merge your changes into to a 'v2.0.0-alpha' branch, so I can add some commits to restore the README to the way I'm happiest with it being. (Happy to sort out how to give you credit/attribution in the way you like best, too.)

Then I'll add you as a collaborator, we release v2.0.0, and you can carry on maintaining and growing this project, if you'd like that?

(I think you have more energy for this than I do, and I would like to see this project continue in some form or other.)

Then you can nuke your old fork. (As I will admit - I mostly just want my old name gone, and that's my primary goal here.)

And then - if you're still curious - we'll roadmap the way forward for the work in my old branch. As a different (if derived) project, as I do agree with you there, this does make more sense this way.

(I need to build just a little bit more trust with you first, I think, before I show you my code there.)

Does this sound reasonable?

**Comment by sgkasselau** [comment]
> Speaking of licenses, the creative commons licenses is not a common license used in software. Can you clarify why you chose it? Why not MIT, for example? Right now, I don't know all the details of this license, but, if possible, I would recommend to change the license to MIT, which is more common, simpler and still requires people to give you attribution.
> 
> I see that the original C++ implementation, which you based your implementation on, also has the same license [here](https://github.com/moridinamael/mc-aixi/blob/master/license.txt), but I don't think that you need to license this package under the same license only because of that.
> 
> The "ShareAlike" part seems to imply that, if you remix, transform or build upon, you must redistribute the contributions under the same license, but the question is: although you based your implementation on the C++ ones, does that imply that you built upon it? I don't think so. I think that building upon, here, means that you develop some software on top of the C++ version, which is not the case. You also didn't remix or transform the original one. You created a completely new software, although inspired by the C++ version.

These are all excellent points, but I'm not a lawyer, let alone an intellectual property lawyer.

I'm not sure where the exact line is for derived works, and given the back and forth on whether even implementing code from API reference documentation is a derived work or not? I didn't want to take a chance, just in case people got litigious.

I put a bit about this in the original README, and I feel this is probably still in our best interests to include this - if even just in doc/LICENCE.md

I'll think on the MIT licence idea. Thanks for the suggestion!

**Comment by nbro** [comment]
> But you can understand how this looked to me, right? Especially when you've gone to such lengths to list other projects in the human-readable documentation - you haven't listed who literally created the codebase you're working on. Not a word, not even a link.
> 
> It felt - and others I asked agreed with me - like you were trying to remove references to me, so that you could claim credit for the whole project.

I disagree with your insinuations. There's a link to your original repo. In fact, I created a fork, so the link is there. Second, I removed the section **Contact the author** for the reasons that I already mentioned - you would not have accepted pull request and I would separately work on this fork, so why would I leave such section on my version of the README.md? Third, if I really wanted to remove all references to you and claim the work mine, I would have done that also in the setup.py, which I am fully aware has your name. I think your accusations are unfair, and I will think about collaborating with you - I don't want to collaborate with someone that always has the bad thoughts about me or what I do.

**Comment by sgkasselau** [comment]
@nbro I am disappointed to hear this.

(Especially when I was trying so carefully to explain where I'm coming from in non-presumptive language, and work with you collaboratively despite this!)

If you change your mind later, please do let me know.


And as a reminder - these conditions are non-negotiable for your continued use of this codebase:

- restore my author credit (as SG Kassel) to the README files on your fork
- rewrite the author name on the commit history for my commits to SG Kassel

This last point is easy to resolve with a little bit of command line work and a force push, as detailed here:

https://dev.to/chrisvasqm/how-to-change-the-author-of-all-your-commits-2j7a

**Comment by nbro** [comment]
@sgkasselau As a reminder, I can modify your code as I wish according to the "creative commons attribution-sharealike 3.0" as long as I give proper attribution to you, which I already give in the `setup.py`, so you cannot tell me how I can change my version of the code, when you made it open-source. I will continue to work on my version and I don't have to change my version of the README or any other file in my fork only to make you happy. If you kindly ask me to do it, I may do it, but I don't have to do it. I don't have to write your name everywhere in my version of the repo. I only need to give proper attribution, which I am EFFECTIVELY already doing - these are facts, not inventions.

**Comment by nbro** [comment]
@sgkasselau Given that I don't want this discussion to continue forever and don't want to make a tempest in a teapot only because of your misinterpretations of my actions, 

1. I will change your name in my version of the repo (to make you happy), and
2. I will create a `CONTRIBUTORS.md` file (probably under `docs`), which emphasizes that you're the original author of the repo and I am a new contributor/author, because I think it's fine to have such a file when there is more than one contributor to a codebase.

However, note that you cannot just ask people to do what you want when you make something free, modifiable, etc., and licensed under a license that allows people to modify the code as they want, again, provided that proper attribution is given and the code is still licensed under the same license. I am not an expert in licenses, but you can read here https://creativecommons.org/licenses/by-sa/3.0/ the conditions of the license that you used. I am not infringing any condition of the license, and you should be careful when accusing people and provide facts that support your claims, i.e. facts that show that I am infringing any copyright, which would be unintentionally anyway! - but, as far as I read the license, I am not infringing any condition, so I am not worried at all.

**Comment by sgkasselau** [comment]
@nbro I think you should reread the actual licence very carefully, particular the restrictions in 4 (c) i):

> You must, unless a request has been made pursuant to Section 4(a), **keep intact all copyright notices for the Work and provide, reasonable to the medium or means You are utilizing: (i) the name of the Original Author (or pseudonym, if applicable) if supplied**, and/or if the Original Author and/or Licensor designate another party or parties (e.g., a sponsor institute, publishing entity, journal) for attribution ("Attribution Parties") in Licensor's copyright notice, terms of service or by other reasonable means, the name of such party or parties; 

and I draw your attention particularly to:

> The credit required by this Section 4(c) may be implemented in any reasonable manner; provided, however, that in the case of a Adaptation or Collection, at a minimum such credit will appear, if a credit for all contributing authors of the Adaptation or Collection appears, then as part of these credits **and in a manner at least as prominent as the credits for the other contributing authors**

Your modifications have removed my name, the links to me and my work from where they were. Someone checking out your fork would struggle to find a reference to me, and would instead see your name. Demoting me from prominence from the README file to a file in a subdirectory, is not - to a reasonable person, the standard in civil law - a 'manner at least as prominent'.

(You've also removed Joel Veness from the attribution in the README too, and this isn't appropriate either.)

As such, you are currently in breach of the licence, and under Section 7, your licence to use **and derive works from this code** is automatically terminated.

I have been very gentle with you here, and I have 'asked you kindly' over and over again to do the right thing here.

I have told you what will be required to bring you back into compliance. Your proposed solution is not it.

Have I made myself clear?

**Comment by nbro** [comment]
@sgkasselau 

> keep intact all copyright notices for the Work and provide, reasonable to the medium or means You are utilizing: (i) the name of the Original Author (or pseudonym, if applicable) if supplied

- The copyright notices are there. 
- The name the original author is there

> and in a manner at least as prominent as the credits for the other contributing authors

- Your name is in the `setup.py` (and now also in `CONTRIBUTORS.md` with an emphases "**original author**")

Every intelligent person that is familiar with Github would understand that 

1. mine is a fork of your repo (so it implies it's not an original), 
   1. I am therefore not the original author, 
   2. Therefore, there's a link to the original repo,
4. the license is under doc (if you search a little bit) and it was not changed, 
5. I am not saying anywhere that I am the original author, 
6. your name is in setup.y (and now also in `CONTRIBUTORS.md` with an emphases "**original author**")
7.  the name of Joel Veness is still in the README.md (although I have no idea why I would need to give attribution to him in this case and I have no idea why you're claiming that I am not giving him attribution)

So, by having changed your name (I really didn't have to do this according to the license but I made you a favour) in my fork and added the `CONTRIBUTORS.md` file that clearly states that you're the original author (this was also a favour - I didn't have to do this, as the `setup.py` already states that you're an author), there's nothing more to add from my side (and I am tired of repeating the same things) - I can modify the code as a I please - the changes that I make can clearly be seen from Github.

Having said that, I decided to keep working on my repo and make it the actual good one (as I had said), instead of contributing to a repo that is dead and nobody used. I will not waste anymore time here.

**Pull request closed without merging**
